package com.energyhub.interview.setgame;

import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertTrue;

/**
 * Unit tests for PileOfCards class
 */
public class PileOfCardsTest {
    private PileOfCards testPile;

    /**
     * setUp function for PileOfCards Unit Tests
     *
     * Instantiates a PileOfCards with 10 randomly generated cards
     */
    @Before
    public void setUp() {
        testPile = new PileOfCards(10);
    }

    /**
     * Unit test for getHands()
     *
     * Ensures that the powerset generated by getHands() does not produce duplicate hands and produces the correct
     * number of hands (2^N)
     * @throws Exception
     */
    @Test
    public void getHands() throws Exception {
        List<Hand> list = testPile.getHands(-1);
        assertTrue(list.size() == Math.pow(2, 10));
        for(int i = 0; i < list.size(); i++)
            for(int j = 0; j < list.size(); j++)
                if(i != j)
                    assertTrue(list.get(i).compareTo(list.get(j)) != 0);
    }

    /**
     * Unit test for pruneHands()
     *
     * Ensures that the list returned by pruneHands() only contains hands of the specified length by the parameter
     * passed into pruneHands().
     * @throws Exception
     */
    @Test
    public void pruneHands() throws Exception {
        List<Hand> hands = testPile.getHands(3);
        for(int i = 0; i < hands.size(); i++)
            assertTrue(hands.get(i).size() == 3);
    }
}